# TODO: Add isort
# See: https://github.com/PyCQA/isort/pull/2122

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-ast
      - id: trailing-whitespace
      - id: pretty-format-json
        args:
          - "--autofix"

  - repo: https://github.com/myint/autoflake
    rev: v2.2.0
    hooks:
      - id: autoflake
        args:
          - --in-place
          - --remove-unused-variables
          - --remove-all-unused-imports
          - --expand-star-imports

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
